config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # the do block is added only for the pin votes.
    resources :pins do
      member do
        put "like", to: "pins#upvote"
      end
    end
    
    root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    #this is for the votable gem
    acts_as_votable
    #each pin can only have one user
    belongs_to :user
    #this is from the paperclip gem page, you can also put a default image , default_url: "/images/:style/missing.png"
    #just changed :avatar to :image for clarity reason.
    has_attached_file :image, styles: { medium: "300x300>"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # A user can have many pins, but each pin can only have one User.
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :authenticate_user!
    #specifies where find_pin is allow to start. 
    before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote] 
    
    def index
        #displays all Pins in descending order of creation (newest first)
        @pins= Pin.all.order("created_at DESC")
    end
    
    def show
    
    end
    
    def new
        #@pin = Pin.new once user.id is required this code doesn't work anymore
        #this method will record the user id in the Pins table
        @pin = current_user.pins.build
    end
    
    def create
        #once devise is install and a user ID must be put in the pin table this code doesn't work
        #@pin= Pin.new(pin_params)
        @pin = current_user.pins.build(pin_params)
        if @pin.save
            #flash messages for is in layouts/_messages.html.erb
            flash[:success] = "Pin was successfully created"
            redirect_to @pin
        else
        render 'new'
        end
    end
    
    def edit
        #there is nothing here since the before action already finds the pin we want to edit.
    end
    
    def update
        #since we use the find_pin before action we don't need to specify it.
        if @pin.update(pin_params)
            #flash has to be before redirecting, otherwise it will give a string conversion error.
             flash[:success] = "Pin was successfully update"
             redirect_to @pin
        else
            render 'edit'
        end
    end
    
    def destroy
        if 
            @pin.destroy
            flash[:success] = "Pin was successfully deleted"
            redirect_to root_path
        else
            flash[:danger] = "Pin could not be deleted"
            redirect_to edit_pin_path
        end
        
    end
    
    def upvote
		@pin.upvote_by current_user
		redirect_to :back
    end
    
    
    private
    
    def pin_params
        #permits the pins components before their creation.
        params.require(:pin).permit(:title, :description, :image)
    end
    
    private
    #since we need the find_pin method for update, show, edit and destror action we create a specific method so as not to repeat ourselves.
    def find_pin
        @pin = Pin.find(params[:id])
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <!-- we refer to flash in the controllers -->
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}"if msg.is_a?(String) %>
      </div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><%= link_to "Pin board", root_path, class:"navbar-brand" %></a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                <li><%= link_to "New Pin", new_pin_path %></li>
                <li><%= link_to "Account", edit_user_registration_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                <%else%>
                <li><%= link_to "Sign Up", new_user_session_path %></li>
                <li><%= link_to "Log In", new_user_registration_path %></li>
                <%end%>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    <div class="container">
     
        <%= yield %>
    </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: {multipart: true } do |f| %>
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :image, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control'} %>
    <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/pins/edit.html.erb
<div class="col-md-8 col-md-offset-2">
    
    <div class="well">
        <h1 class="text-center">Edit Pin</h1>
    </div>
    <%= render 'form' %>
    <%= link_to "Cancel", root_path, class:"btn btn-warning" %>

</div>

app/views/pins/index.html.erb
<h1>All the Pins there are to see</h1>

<div class="transitions-enabled" id="pins"> <!-- this class and ID are used by the masonry gem -->
  <% @pins.each do |pin| %>
    <div class="box panel panel-default"> <!-- pin div block -->
      <% if pin.image.present? %>
      <%= link_to (image_tag pin.image.url), pin %>
      <% else %>
      <%end%>
      <h2>
        <%= link_to pin.title, pin %>
      </h2>
      <% if pin.user.present? %>
      <p class="user">
        Submitted by <%= pin.user.email %>
      </p>
      <%else%>
      <%end%>
    </div>  <!-- pin div block -->
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
    
    <div class="well">
        <h1 class="text-center">New Pin</h1>
    </div>
    <%= render 'form' %>
    <%= link_to "Back", root_path, class:"btn btn-warning" %>

</div>

    

app/views/pins/show.html.erb
<div class="row" id="pin_show">    
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            
       
            <div class="panel-body">
                <h2><%= @pin.title %></h2>
                <p><%= @pin.description %></p>
            </div>
        <!-- this 'if' block is to prevent errors in case the pin has no picture -->
        <% if @pin.image.present? %>
        <div class="panel-heading pin_image">
            <%= image_tag @pin.image.url %>
        </div>
        <%else%>
        <p>No picture for this pin.</p>
        <%end%>
            <div class="panel-footer">
                <div class="row">
                <!-- this 'if' block is only to prevent errors in development, no Pin should be without user in production -->
                    <% if @pin.user_id.present? %>
                
                    <div class="col-md-6">
                        <p class="user">
                            Submited by: <%= @pin.user.email %>
                        </p>
                    </div>
                
                    <% else %>
                    <p class="text-center">No User Recorded</p>
                    <%end%> <!--end if block -->
                    <div class="col-md-6"> <!-- btn group -->
                        <div class="btn-group pull-right"> <!-- groups the button to the right for improved aesthetic -->
                            <%= link_to "Back", root_path, class:"btn btn-primary" %>
                            <% if user_signed_in? %> <!-- Only the pin's user can delete it -->
                            <%= link_to like_pin_path(@pin), method: :put, class:"btn btn-default" do %>
                                <span class="glyphicon glyphicon-heart"> </span>
                                <%= @pin.get_upvotes.size %>
                                <%end%>
                            <%= link_to "Edit", edit_pin_path, class:"btn btn-warning" %>
                            <!--The delete button is specific a bit here it sends the DELETE html method to the pin path -->
                            <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure" }, class:"btn btn-danger" %>
                            <%end%>
                        </div>
                    </div> <!-- btn group -->
                </div>  <!-- footer's row -->   
            </div> <!-- footer -->
        </div> <!-- panel dflt-->
    </div> <!-- col-md and offset -->
</div><!-- row id pin_show -->